package com.codename1.webserver.demo;


import com.codename1.io.File;
import com.codename1.io.FileSystemStorage;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.io.Util;
import com.codename1.ui.BrowserComponent;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BorderLayout;
import java.io.IOException;
import com.codename1.webserver.WebServer;
import java.io.ByteArrayInputStream;
import java.io.OutputStream;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class CN1WebserverDemo {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
        
        try {
            initWebsite();
        } catch (IOException ex) {
            Log.e(ex);
        }
        
        server = new WebServer(new File("httpdocs").getAbsolutePath(), 8888);
        
    }
    
    private WebServer server;
    
    private void initWebsite() throws IOException {
        FileSystemStorage fs = FileSystemStorage.getInstance();
        File docRoot = new File("httpdocs");
        delTree(docRoot);
        docRoot.mkdir();
        String helloContent = "<!doctype html><html><head><title>Hello</title></head><body><h1>Hello World</h1></body></html>";
        File indexHtml = new File(docRoot, "index.html");
        writeStringToFile(indexHtml, helloContent);
        
    }
    
    private void writeStringToFile(File file, String content) throws IOException {
        FileSystemStorage fs = FileSystemStorage.getInstance();
        try (OutputStream os = fs.openOutputStream(file.getAbsolutePath())) {
            Util.copy(new ByteArrayInputStream(content.getBytes("UTF-8")), os);
        }
        
    }
    
    private void delTree(File file) {
        if (file.isDirectory()) {
            for (File f : file.listFiles()) {
                delTree(f);
            }
        }
        file.delete();
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        server.start();
        Form hi = new Form("Hi World", new BorderLayout());
        BrowserComponent bc = new BrowserComponent();
        bc.setURL("http://localhost:8888/index.html");
        hi.add(BorderLayout.CENTER, bc);
        
        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
        server.stop();
    }
    
    public void destroy() {
    }

}
